In [159]:
import json
import gradio as gr
import numpy as np
import requests
import pandas as pd
import pymongo
import names
import random
import pickle

In [170]:
# Load model
filename = 'undersampling_lengkap.pkl'
with open(filename, 'rb') as f:
    model = pickle.load(f)

In [171]:
# Connect to mongoDB
# MONGODB_URI = "mongodb+srv://if5171:MLDSAI@datingappcluster.oe2g2ap.mongodb.net/?retryWrites=true&w=majority"

# client = pymongo.MongoClient(MONGODB_URI) 
# db = client['datingDB']
# print("Database loaded")
# details = db['details'].find_one()
# users = db['users'].find()

# strToNum = details['strToNum']
# numToStr = details['numToStr']

In [250]:
# Mapping attribute
details = {
    "numToStr": {
        "gender": {
            "1": "Male",
            "2": "Female"
        },
        "field": {
            "1": "Law",
            "2": "Math",
            "3": "Social Science, Psychologist",
            "4": "Medical Science, Pharmaceuticals, and Bio Tech",
            "5": "Engineering",
            "6": "English/Creative Writing/ Journalism",
            "7": "History/Religion/Philosophy",
            "8": "Business/Econ/Finance",
            "9": "Education, Academia",
            "10": "Biological Sciences/Chemistry/Physics",
            "11": "Social Work",
            "12": "Undergrad/undecided",
            "13": "Political Science/International Affairs",
            "14": "Film",
            "15": "Fine Arts/Arts Administration",
            "16": "Languages",
            "17": "Architecture",
            "18": "Other"
        },
        "race": {
            "1": "Black/African American",
            "2": "European/Caucasian-American",
            "3": "Latino/Hispanic American",
            "4": "Asian/Pacific Islander/Asian-American",
            "5": "Native American",
            "6": "Other"
        },
        "go_out": {
            "1": "Several times a week",
            "2": "Twice a week",
            "3": "Once a week",
            "4": "Twice a month",
            "5": "Once a month",
            "6": "Several times a year",
            "7": "Almost never"
        },

        "date": {
            "1": "Several times a week",
            "2": "Twice a week",
            "3": "Once a week",
            "4": "Twice a month",
            "5": "Once a month",
            "6": "Several times a year",
            "7": "Almost never"
        },

        "goal": {
            "1": "Seemed like a fun night out",
            "2": "To meet new people",
            "3": "To get a date",
            "4": "Looking for a serious relationship",
            "5": "To say I did it",
            "6": "Other"
        },
        "career": {
            "1": "Lawyer",
            "2": "Academic/Research",
            "3": "Psychologist ",
            "4": "Doctor/Medicine",
            "5": "Engineer",
            "6": "Creative Arts/Entertainment",
            "7": "Banking/Consulting/Finance/Marketing/Business/CEO/Entrepreneur/Admin",
            "8": "Real Estate",
            "9": "International/Humanitarian Affairs",
            "10": "Undecided",
            "11": "Social Work",
            "12": "Speech Pathology",
            "13": "Politics",
            "14": "Pro sports/Athletics",
            "15": "Other",
            "16": "Journalism",
            "17": "Architecture"
        }


    },
    "strToNum": {
        "gender": {
            "Male": "1",
            "Female": "2"
        },
        "field": {
            "Law": "1",
            "Math": "2",
            "Social Science, Psychologist": "3",
            "Medical Science, Pharmaceuticals, and Bio Tech": "4",
            "Engineering": "5",
            "English/Creative Writing/ Journalism": "6",
            "History/Religion/Philosophy": "7",
            "Business/Econ/Finance": "8",
            "Education, Academia": "9",
            "Biological Sciences/Chemistry/Physics": "10",
            "Social Work": "11",
            "Undergrad/undecided": "12",
            "Political Science/International Affairs": "13",
            "Film": "14",
            "Fine Arts/Arts Administration": "15",
            "Languages": "16",
            "Architecture": "17",
            "Other": "18"

        },

        "race": {
            "Black/African American": "1",
            "European/Caucasian-American": "2",
            "Latino/Hispanic American": "3",
            "Asian/Pacific Islander/Asian-American": "4",
            "Native American": "5",
            "Other": "6"
        },

        "go_out": {
            "Several times a week": "1",
            "Twice a week": "2",
            "Once a week": "3",
            "Twice a month": "4",
            "Once a month": "5",
            "Several times a year": "6",
            "Almost never": "7"
        },
        "date": {
            "Several times a week": "1",
            "Twice a week": "2",
            "Once a week": "3",
            "Twice a month": "4",
            "Once a month": "5",
            "Several times a year": "6",
            "Almost never": "7"
        },

        "goal": {
            "Seemed like a fun night out": "1",
            "To meet new people": "2",
            "To get a date": "3",
            "Looking for a serious relationship": "4",
            "To say I did it": "5",
            "Other": "6"
        },
        "career": {
            "Lawyer": "1",
            "Academic/Research": "2",
            "Psychologist ": "3",
            "Doctor/Medicine": "4",
            "Engineer": "5",
            "Creative Arts/Entertainment": "6",
            "Banking/Consulting/Finance/Marketing/Business/CEO/Entrepreneur/Admin": "7",
            "Real Estate": "8",
            "International/Humanitarian Affairs": "9",
            "Undecided": "10",
            "Social Work": "11",
            "Speech Pathology": "12",
            "Politics": "13",
            "Pro sports/Athletics": "14",
            "Other": "15",
            "Journalism": "16",
            "Architecture": "17"
        }

    }
}

In [261]:
# Randomize users profile
users = []
for i in range(40):
    user = dict()
    if i % 2 == 0:
        gender_str = "female"
        gender = 2
    else:
        gender_str = "male"
        gender = 1
    
    user['name'] = names.get_full_name(gender=gender_str)
    user['gender'] = gender
    user['age'] = random.randint(20, 36)
    user['race'] = random.randint(1, 6)
    user['field'] = random.randint(1, 18)
    user['career'] = random.randint(1, 17)
    user['bio'] = "Hey!, I'm " + user['name']
    user['go_out'] = random.randint(1, 7)
    user['date'] = random.randint(1, 7)
    user['goal'] = random.randint(1, 6)
    user['imprace'] = random.randint(1, 10)
    user['imprelig'] = random.randint(1, 10)
    
    users.append(user)
    
with open('users.json', 'w') as fp:
    json.dump(users, fp)

In [262]:
Gender = "Male"
for key, value in details['strToNum']['gender'].items():
    a = Gender.replace(key, value)
print(a)

Male

In [263]:
details['numToStr']['gender']['1']

'Male'

In [264]:
transformed_user['gender'] = details['strToNum']['gender'][str(user['gender'])]

KeyError: '1'

In [265]:
def transform_str_to_num(user):
    transformed_user = {}
    transformed_user['name'] = user['name']
    transformed_user['gender'] = details['strToNum']['gender'][user['gender']]
    transformed_user['age'] = user['age']
    transformed_user['race'] = details['strToNum']['race'][user['race']]
    transformed_user['field'] = details['strToNum']['field'][user['field']]
    transformed_user['career'] = details['strToNum']['career'][user['career']]
    transformed_user['bio'] = user['bio']
    transformed_user['date'] = details['strToNum']['date'][user['date']]
    transformed_user['go_out'] = details['strToNum']['go_out'][user['go_out']]
    transformed_user['goal'] = details['strToNum']['goal'][user['goal']]
    transformed_user['imprace'] = user['imprace']
    transformed_user['imprelig'] = user['imprelig']
    
    return transformed_user

In [266]:
def transform_num_to_str(user):
    transformed_user = {}
    transformed_user['name'] = user['name']
    transformed_user['gender'] = details['numToStr']['gender'][str(user['gender'])]
    transformed_user['age'] = user['age']
    transformed_user['race'] = details['numToStr']['race'][str(user['race'])]
    transformed_user['field'] = details['numToStr']['field'][str(user['field'])]
    transformed_user['career'] = details['numToStr']['career'][str(user['career'])]
    transformed_user['bio'] = user['bio']
    transformed_user['date'] = details['numToStr']['date'][str(user['date'])]
    transformed_user['go_out'] = details['numToStr']['go_out'][str(user['go_out'])]
    transformed_user['goal'] = details['numToStr']['goal'][str(user['goal'])]
    transformed_user['imprace'] = user['imprace']
    transformed_user['imprelig'] = user['imprelig']
    
    return transformed_user

In [267]:
def merge_user(user1, user2):
    '''
    Transform data from user and partner by merging necessary info into a row
    '''
    age_o = user2['age']
    race_o = user2['race']
    age = user1['age']
    field_cd = user1['field']
    race = user1['race']
    imprace = user1['imprace']
    goal = user1['goal']
    career_c = user1['career']
    field_cd_o = user2['field']
    imprace_o = user2['imprace']
    goal_o = user2['goal']
    career_c_o = user2['career']
    go_out = user1['go_out']
    date = user1['date']
    imprelig = user1['imprelig']
    imprelig_o = user2['imprelig']
    samerace = int(race == race_o)
    go_out_o = user2['go_out']
    date_o = user2['date']
    
    return [samerace, age_o, race_o, age, field_cd, race, imprace, goal, career_c, field_cd_o, imprace_o, goal_o, career_c_o, go_out, date, imprelig, imprelig_o, go_out_o, date_o]

In [268]:
# def merge_user_old(user1, user2):
#     '''
#     Transform data from user and partner by merging necessary info into a row
#     '''
#     gender = user1['gender']
#     race = user1['race']
#     race_o = user2['race']
#     age = user1['age']
#     age_o = user2['age']
#     go_out = user1['go_out']
#     date = user1['date']
#     goal = user1['goal']
#     int_corr = random.random() # Korelasi masih dummy
#     samerace = int(race == race_o)
#     field_cd = user1['field']
#     imprace = user1['imprace']
#     imprelig = user1['imprelig']
    
#     return [gender, race, race_o, age, age_o, go_out, date, goal, int_corr, samerace, field_cd, imprace, imprelig]

In [269]:
def find_partners(user):
    '''
    Take partners based on gender
    If the user is male, take the female users
    If the user is female, take the male users
    '''
    partners = []
    for partner in users:
        if str(user['gender']) == '1':
            if str(partner['gender']) == '2':
                partners.append(partner)
        elif str(user['gender']) == '2':
            if str(partner['gender']) == '1':
                partners.append(partner)   
    return partners

In [282]:
def recommendations(user, partners):
    '''
    Predict match probability for each partners 
    '''
    partners = np.array(partners)
    # Transform data type for prediction 
    X = []
    for p in partners:
        merge_result = merge_user(user, p)
        X.append(merge_result)
        
    # Predict the target 'match' 
    results = model.predict_proba(X)
    results = results.transpose()
    results = results[1]
    df_results = pd.DataFrame(results)
    df_results.rename(columns={0: "match"})
    transformed_partners = []
    
    # Transform partners before showing to the app
    for p in partners:
        transformed = transform_num_to_str(p)
        transformed_partners.append(transformed)
    df_partners = pd.DataFrame(transformed_partners)
    df_partners = pd.merge(df_partners, df_results, left_index=True, right_index=True)
    
    # Sort partners based on match label 
    sorted_partners = df_partners.sort_values(0, ascending=False)
    return sorted_partners

In [278]:
def inputProfile(Name, Gender, Age, Race, Field, Career, Bio, GoOut, Date, Goal, ImpRelig, ImpRace):
    new_user = dict()
    new_user['name'] = Name
    new_user['gender'] = Gender
    new_user['age'] = Age
    new_user['race'] = Race
    new_user['field'] = Field
    new_user['career'] = Career
    new_user['bio'] = Bio
    new_user['go_out'] = GoOut
    new_user['date'] = Date
    new_user['goal'] = Goal
    new_user['imprace'] = ImpRelig
    new_user['imprelig'] = ImpRace
    
    transformed_user = transform_str_to_num(new_user)
    partners = find_partners(transformed_user)
    results = recommendations(transformed_user, partners)
    
    print(results)

    return results

In [285]:
# Input profile   
demo = gr.Interface(
    inputProfile,
    title="Companero",
    description="Input your Profile, Behavior, and Preferences here!",
    inputs = [
        gr.Textbox(lines=1, placeholder="Your name here..."),
        gr.Radio(["Male", "Female"]),
        gr.Slider(20, 35),
        gr.Radio(["Black/African American",
                "European/Caucasian-American",
                "Latino/Hispanic American",
                "Asian/Pacific Islander/Asian-American",
                "Native American",
                "Other"]),
        gr.Radio(["Law",
                "Math",
                "Social Science, Psychologist",
                "Medical Science, Pharmaceuticals, and Bio Tech", 
                "Engineering",  
                "English/Creative Writing/ Journalism", 
                "History/Religion/Philosophy", 
                "Business/Econ/Finance", 
                "Education, Academia", 
                "Biological Sciences/Chemistry/Physics",
                "Social Work", 
                "Undergrad/undecided",
                "Political Science/International Affairs", 
                "Film",
                "Fine Arts/Arts Administration",
                "Languages",
                "Architecture",
                "Other"]),
        gr.Radio(["Lawyer",
                "Academic/Research",
                "Psychologist ",
                "Doctor/Medicine",
                "Engineer",
                "Creative Arts/Entertainment",
                "Banking/Consulting/Finance/Marketing/Business/CEO/Entrepreneur/Admin",
                "Real Estate",
                "International/Humanitarian Affairs",
                "Undecided",
                "Social Work",
                "Speech Pathology",
                "Politics",
                "Pro sports/Athletics",
                "Other",
                "Journalism",
                "Architecture"]),
        gr.Textbox(lines=5, placeholder="Your bio description here..."),
        gr.Radio(["Several times a week",
                  "Twice a week",
                  "Once a week",
                  "Twice a month",
                  "Once a month",
                  "Several times a year",
                  "Almost never",]),
        gr.Radio(["Several times a week",
                  "Twice a week",
                  "Once a week",
                  "Twice a month",
                  "Once a month",
                  "Several times a year",
                  "Almost never",]),
        gr.Radio(["Seemed like a fun night out",
                "To meet new people",
                "To get a date",
                "Looking for a serious relationship",
                "To say I did it",
                "Other"]),
        gr.Slider(0, 10),
        gr.Slider(0, 10)
    ],
    outputs = "text"    
)

demo.launch(share=True)

Running on local URL:  http://127.0.0.1:7903
Running on public URL: https://e52b622c81a2bb0f.gradio.app

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces

C:\Users\TEMP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

                  name  gender  age                                   race  \
1           Opal Green  Female   34                        Native American
5           Lisa Moore  Female   36               Latino/Hispanic American
14       Mayme Pacheco  Female   32                        Native American
12          Stacy Pope  Female   26  Asian/Pacific Islander/Asian-American
4        Carol Stanton  Female   32            European/Caucasian-American
11        Denise Newby  Female   34                                  Other
16    Beatrice Nolting  Female   34            European/Caucasian-American
13  Catherine Bonnette  Female   27            European/Caucasian-American
18         Rose Krause  Female   22               Latino/Hispanic American
7         Alma Gurnett  Female   28                 Black/African American
17      Glenna Colston  Female   31                        Native American
19       Jennifer Frey  Female   28                                  Other
3           Jewel Shin  Female   35                 Black/African American
2     Sharon Holsopple  Female   25                                  Other
9          Karen Never  Female   25                        Native American
0        Deann Maynard  Female   35               Latino/Hispanic American
15       Holly Jackson  Female   23                        Native American
6    Frances Delatorre  Female   30                 Black/African American
8        Carrie Colley  Female   23            European/Caucasian-American
10        Marilyn Moss  Female   23            European/Caucasian-American

                                             field  \
1                            Business/Econ/Finance
5                                      Engineering
14                                    Architecture
12            English/Creative Writing/ Journalism
4                                             Film
11                                       Languages
16                                    Architecture
13                     History/Religion/Philosophy
18                                            Math
7                              Undergrad/undecided
17                                            Film
19  Medical Science, Pharmaceuticals, and Bio Tech
3            Biological Sciences/Chemistry/Physics
2                      History/Religion/Philosophy
9                    Fine Arts/Arts Administration
0                              Undergrad/undecided
15           Biological Sciences/Chemistry/Physics
6          Political Science/International Affairs
8                            Business/Econ/Finance
10                   Fine Arts/Arts Administration

                                               career  \
1                                   Academic/Research
5                                              Lawyer
14                                             Lawyer
12                                    Doctor/Medicine
4                                       Psychologist
11                                    Doctor/Medicine
16                                    Doctor/Medicine
13  Banking/Consulting/Finance/Marketing/Business/...
18                                  Academic/Research
7                                              Lawyer
17                        Creative Arts/Entertainment
19                                        Real Estate
3                                   Academic/Research
2   Banking/Consulting/Finance/Marketing/Business/...
9                                       Psychologist
0                         Creative Arts/Entertainment
15  Banking/Consulting/Finance/Marketing/Business/...
6                  International/Humanitarian Affairs
8                                              Lawyer
10                                           Politics

                             bio                  date                go_out  \
1           Hey!, I'm Opal Green          Once a month           Once a week
5           Hey!, I'm Lisa Moore  Several times a year         Twice a month
14       Hey!, I'm Mayme Pacheco           Once a week          Twice a week
12          Hey!, I'm Stacy Pope  Several times a week           Once a week
4        Hey!, I'm Carol Stanton          Twice a week           Once a week
11        Hey!, I'm Denise Newby           Once a week          Once a month
16    Hey!, I'm Beatrice Nolting          Twice a week          Once a month
13  Hey!, I'm Catherine Bonnette         Twice a month          Once a month
18         Hey!, I'm Rose Krause          Almost never          Once a month
7         Hey!, I'm Alma Gurnett  Several times a week         Twice a month
17      Hey!, I'm Glenna Colston           Once a week  Several times a year
19       Hey!, I'm Jennifer Frey  Several times a year  Several times a week
3           Hey!, I'm Jewel Shin         Twice a month          Once a month
2     Hey!, I'm Sharon Holsopple  Several times a week          Almost never
9          Hey!, I'm Karen Never  Several times a year         Twice a month
0        Hey!, I'm Deann Maynard          Once a month  Several times a week
15       Hey!, I'm Holly Jackson  Several times a week  Several times a year
6    Hey!, I'm Frances Delatorre         Twice a month           Once a week
8        Hey!, I'm Carrie Colley          Almost never          Almost never
10        Hey!, I'm Marilyn Moss           Once a week  Several times a week

                                  goal  imprace  imprelig     0
1          Seemed like a fun night out        6         5  0.35
5                        To get a date        4        10  0.34
14         Seemed like a fun night out        8         1  0.32
12                               Other        8         4  0.30
4                      To say I did it        3         6  0.29
11                  To meet new people        2         3  0.29
16                               Other        1         4  0.28
13                     To say I did it        2         6  0.26
18                  To meet new people        7         4  0.25
7   Looking for a serious relationship        9         5  0.25
17                       To get a date        6         6  0.24
19                     To say I did it        3        10  0.23
3                      To say I did it        5         4  0.23
2                        To get a date        8         7  0.22
9   Looking for a serious relationship        9         4  0.22
0                                Other        5         5  0.20
15                       To get a date        3         4  0.20
6                      To say I did it        8         2  0.20
8                      To say I did it        8         9  0.18
10                     To say I did it        9         2  0.18

In [274]:
with gr.Blocks() as demo:
    for p in results:
        with gr.Row():
            gr.Image("person.png")
            text = f'''
{p['name']}, {p['gender']}, {p['age']} years old
{p['field']}
{p['career']}
{p['bio']}
            '''
            text = 'namaku'
            gr.Text(text)
demo.launch()

0.8
0.9
0.3
Running on local URL:  http://127.0.0.1:7901

To create a public link, set `share=True` in `launch()`.

```
Profile
- Name (text)
- Gender (radio)
- Profile picture (image)
- Race (radio)
- Field (radio)
- Bio (text 5 lines)

Behavior
- Go out (radio)
- Date (radio)

Preferences
- ImpRelig (radio scale 1-10)
- ImpRace (radio scale 1-10)
```

In [273]:
# # Contoh predict
# X = np.array([[1,4,2,4,5,6,2,4,6,3,4,3,2],
#               [1,4,2,5,9,5,6,2,4,6,3,4,3],
#               [4,2,5,9,5,6,2,4,6,3,4,3,8],
#               [9,3,1,4,2,5,9,5,6,2,4,6,3]])
# result = model.predict_proba(X).transpose()[1]
# df_result = pd.DataFrame(result)
# df_result

In [283]:
# inputProfile(Name, Gender, Age, Race, Field, Career, Bio, GoOut, Date, Goal, ImpRelig, ImpRace)
inputProfile("Holly", 
             "Female", 
             23, 
             "Asian/Pacific Islander/Asian-American", 
             "Engineering",
             "Engineer",
             "Apa kabar kalian semua",
             "Twice a week",
             "Twice a week",
             "To meet new people",
             9,
             9)

                  name gender  age                                   race  \
18          John Silva   Male   34                 Black/African American
3       Daniel Wegener   Male   23  Asian/Pacific Islander/Asian-American
16    Timothy Crawford   Male   35            European/Caucasian-American
4      Thomas Atchison   Male   30  Asian/Pacific Islander/Asian-American
17    Kendrick Mcelroy   Male   25                 Black/African American
14       Gary Phillips   Male   21                                  Other
10       Lonnie Cuevas   Male   26                 Black/African American
6   William Hunsberger   Male   27                 Black/African American
11      Vincent Burton   Male   22            European/Caucasian-American
8          Percy Heath   Male   30                 Black/African American
12         Kevin Wylie   Male   27               Latino/Hispanic American
15    Charles Madrigal   Male   30                                  Other
19     Jeffery Crocker   Male   20                 Black/African American
9       Rodney Kleypas   Male   35                        Native American
5            Juan Hill   Male   24                        Native American
1         Albert Lewis   Male   23                 Black/African American
2            Ben Croft   Male   24                        Native American
0            John Bray   Male   20            European/Caucasian-American
7         Dustin Reyes   Male   23            European/Caucasian-American
13        Scott Custer   Male   30                        Native American

                                             field  \
18                                            Math
3                                             Math
16                                            Math
4                                              Law
17  Medical Science, Pharmaceuticals, and Bio Tech
14         Political Science/International Affairs
10                                           Other
6                                     Architecture
11                                            Film
8                                      Engineering
12                             Education, Academia
15                                           Other
19                                            Film
9                    Fine Arts/Arts Administration
5                                     Architecture
1                                             Film
2                                             Film
0                              Undergrad/undecided
7                                        Languages
13                                            Film

                                               career  \
18  Banking/Consulting/Finance/Marketing/Business/...
3                                         Real Estate
16                                             Lawyer
4                                       Psychologist
17                                        Social Work
14  Banking/Consulting/Finance/Marketing/Business/...
10                                             Lawyer
6                                        Architecture
11                                    Doctor/Medicine
8                                          Journalism
12                                          Undecided
15                                          Undecided
19                        Creative Arts/Entertainment
9                                         Real Estate
5                                            Politics
1                                              Lawyer
2                                           Undecided
0                                        Architecture
7                                       Psychologist
13                                          Undecided

                             bio                  date                go_out  \
18          Hey!, I'm John Silva           Once a week          Twice a week
3       Hey!, I'm Daniel Wegener         Twice a month  Several times a week
16    Hey!, I'm Timothy Crawford          Twice a week          Once a month
4      Hey!, I'm Thomas Atchison  Several times a week          Twice a week
17    Hey!, I'm Kendrick Mcelroy          Twice a week          Once a month
14       Hey!, I'm Gary Phillips         Twice a month  Several times a week
10       Hey!, I'm Lonnie Cuevas         Twice a month          Twice a week
6   Hey!, I'm William Hunsberger          Twice a week  Several times a year
11      Hey!, I'm Vincent Burton  Several times a year          Once a month
8          Hey!, I'm Percy Heath          Twice a week  Several times a year
12         Hey!, I'm Kevin Wylie           Once a week           Once a week
15    Hey!, I'm Charles Madrigal  Several times a year           Once a week
19     Hey!, I'm Jeffery Crocker         Twice a month           Once a week
9       Hey!, I'm Rodney Kleypas          Twice a week          Once a month
5            Hey!, I'm Juan Hill  Several times a year  Several times a week
1         Hey!, I'm Albert Lewis          Almost never  Several times a year
2            Hey!, I'm Ben Croft          Once a month           Once a week
0            Hey!, I'm John Bray  Several times a week          Once a month
7         Hey!, I'm Dustin Reyes          Almost never           Once a week
13        Hey!, I'm Scott Custer         Twice a month           Once a week

                                  goal  imprace  imprelig     0
18                               Other        8         7  0.32
3                   To meet new people        3         1  0.31
16                     To say I did it        7         1  0.30
4                                Other        8         3  0.29
17                       To get a date        7         7  0.29
14                               Other        2         8  0.27
10  Looking for a serious relationship       10         4  0.26
6                        To get a date       10         7  0.26
11                     To say I did it        8         8  0.26
8                   To meet new people       10         1  0.25
12         Seemed like a fun night out       10         5  0.24
15                               Other        1         8  0.24
19                               Other        2         3  0.23
9                      To say I did it        5        10  0.23
5                   To meet new people        1         6  0.22
1                   To meet new people        6         5  0.21
2   Looking for a serious relationship        9         7  0.20
0   Looking for a serious relationship        8         5  0.20
7                   To meet new people        1         4  0.19
13                       To get a date        8         4  0.17

C:\Users\TEMP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

,name,gender,age,race,field,career,bio,date,go_out,goal,imprace,imprelig,0
18,John Silva,Male,34,Black/African American,Math,Banking/Consulting/Finance/Marketing/Business/...,"Hey!, I'm John Silva",Once a week,Twice a week,Other,8,7,0.32
3,Daniel Wegener,Male,23,Asian/Pacific Islander/Asian-American,Math,Real Estate,"Hey!, I'm Daniel Wegener",Twice a month,Several times a week,To meet new people,3,1,0.31
16,Timothy Crawford,Male,35,European/Caucasian-American,Math,Lawyer,"Hey!, I'm Timothy Crawford",Twice a week,Once a month,To say I did it,7,1,0.30
4,Thomas Atchison,Male,30,Asian/Pacific Islander/Asian-American,Law,Psychologist,"Hey!, I'm Thomas Atchison",Several times a week,Twice a week,Other,8,3,0.29
17,Kendrick Mcelroy,Male,25,Black/African American,"Medical Science, Pharmaceuticals, and Bio Tech",Social Work,"Hey!, I'm Kendrick Mcelroy",Twice a week,Once a month,To get a date,7,7,0.29
14,Gary Phillips,Male,21,Other,Political Science/International Affairs,Banking/Consulting/Finance/Marketing/Business/...,"Hey!, I'm Gary Phillips",Twice a month,Several times a week,Other,2,8,0.27
10,Lonnie Cuevas,Male,26,Black/African American,Other,Lawyer,"Hey!, I'm Lonnie Cuevas",Twice a month,Twice a week,Looking for a serious relationship,10,4,0.26
6,William Hunsberger,Male,27,Black/African American,Architecture,Architecture,"Hey!, I'm William Hunsberger",Twice a week,Several times a year,To get a date,10,7,0.26
11,Vincent Burton,Male,22,European/Caucasian-American,Film,Doctor/Medicine,"Hey!, I'm Vincent Burton",Several times a year,Once a month,To say I did it,8,8,0.26
8,Percy Heath,Male,30,Black/African American,Engineering,Journalism,"Hey!, I'm Percy Heath",Twice a week,Several times a year,To meet new people,10,1,0.25
12,Kevin Wylie,Male,27,Latino/Hispanic American,"Education, Academia",Undecided,"Hey!, I'm Kevin Wylie",Once a week,Once a week,Seemed like a fun night out,10,5,0.24
15,Charles Madrigal,Male,30,Other,Other,Undecided,"Hey!, I'm Charles Madrigal",Several times a year,Once a week,Other,1,8,0.24
19,Jeffery Crocker,Male,20,Black/African American,Film,Creative Arts/Entertainment,"Hey!, I'm Jeffery Crocker",Twice a month,Once a week,Other,2,3,0.23
9,Rodney Kleypas,Male,35,Native American,Fine Arts/Arts Administration,Real Estate,"Hey!, I'm Rodney Kleypas",Twice a week,Once a month,To say I did it,5,10,0.23
5,Juan Hill,Male,24,Native American,Architecture,Politics,"Hey!, I'm Juan Hill",Several times a year,Several times a week,To meet new people,1,6,0.22
1,Albert Lewis,Male,23,Black/African American,Film,Lawyer,"Hey!, I'm Albert Lewis",Almost never,Several times a year,To meet new people,6,5,0.21
2,Ben Croft,Male,24,Native American,Film,Undecided,"Hey!, I'm Ben Croft",Once a month,Once a week,Looking for a serious relationship,9,7,0.20
0,John Bray,Male,20,European/Caucasian-American,Undergrad/undecided,Architecture,"Hey!, I'm John Bray",Several times a week,Once a month,Looking for a serious relationship,8,5,0.20
7,Dustin Reyes,Male,23,European/Caucasian-American,Languages,Psychologist,"Hey!, I'm Dustin Reyes",Almost never,Once a week,To meet new people,1,4,0.19
13,Scott Custer,Male,30,Native American,Film,Undecided,"Hey!, I'm Scott Custer",Twice a month,Once a week,To get a date,8,4,0.17